# Generated by Django 5.1.7 on 2025-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
